### ISSUE TITLE
"You server is inaccessible!"

### ISSUE THREAD

**Issue by polzy** [Wamy-Dev/Mazi#2]
Hi,
Thanks you for you script 

In discord, i have message : "Your Plex Server is not accessible!" with >movie command.
My IP is visible from the WAN http://176.150.XXX.XXX:32400 and i have try with my custom domain and i have same error .. 
![image](https://user-images.githubusercontent.com/1337715/187869659-10d001aa-d4b6-41e7-a90b-df0a724eb20e.png)

I forgot something ?

Thanks

**Comment by Wamy-Dev** [comment]
Have you tried reading the [FAQ](https://github.com/Wamy-Dev/Mazi/wiki/FAQ)? Also please check the "remote" tab in the Plex server you are using and copy the address that is listed there. You will have to click the "Show Advanced" button. Everything should be working, there is just something wrong with your Plex setup, or the URL you gave Mazi.

**Comment by polzy** [comment]
Yes i have 30 users in my plex, i have reading the [FAQ] yes

![image](https://user-images.githubusercontent.com/1337715/187940712-03770428-7f07-486a-aed6-4cc0fac08311.png)

**Comment by Wamy-Dev** [comment]
Are you the owner of the Plex server?

**Comment by polzy** [comment]
Yes I tried disabling MFA, disabling PIN, rebooting, opening ports, shutting down firewall but same problem.
My plex email is not the same on [Mazi](https://mazi.pw/), could that be a problem?

**Comment by Wamy-Dev** [comment]
Can you please send the full ip, or domain that you are trying to use?

**Comment by Wamy-Dev** [comment]
Also, I am looking through the server database, and I don't see an ip that starts with the one you sent in the picture

**Comment by polzy** [comment]
i have try http://xxxxxxx.fr:32400  or   http://xxxxxxx7:32400

can you hide my ip after read please?

![image](https://user-images.githubusercontent.com/1337715/187970390-cc5c03d2-5201-432e-b32c-8f93c941eb73.png)

**Comment by Wamy-Dev** [comment]
Well, neither addresses even respond, so there must be something wrong with your port forwarding.

**Comment by polzy** [comment]
I tried with friends and the ip works fine. 
Too bad, thanks again.
