### ISSUE TITLE
Error getting libraries. Please check that your url is correct

### ISSUE THREAD

**Issue by OrixHusky** [Wamy-Dev/Mazi#4]
I'm having an issue similar to I believe this issue https://github.com/Wamy-Dev/Mazi/issues/2 

whenever I try to add my plex server it is not detecting my libraries. I can confirm that my plex server is up and accessible from outside my local network.

**Comment by Wamy-Dev** [comment]
Hey there, this is a very common problem, but usually requires sharing sensitive details like your email and ip to investigate further. Please join the discord server https://discord.gg/47SnjxgBFb and open a support ticket in #support. I can almost guarantee that the is not a bug and user error.
